<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SignUpRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
//        return [
//            'first_name'=>'required|string|min:4|max:28',
//            'last_name'=>'required|string',
//            'email'=>'required|email|',
//            'password'=>'required|',
//        ];


    }
    public function messages()
    {
//        return [
//            'first_name.required'=>'First Name is needed',
//            'last_name.required'=>'Last Name is needed',
//            'email.required'=>'Email is needed',
//            'password.required'=>'Password is needed',
//
//        ]; // TODO: Change the autogenerated stub
    }
}
$rules = [
    'name' => 'required',
    'email' => 'required|email',
    'message' => 'required|max:250',
];

$customMessages = [
    'required' => 'The :attribute field is required.'
];

$this->validate($request, $rules, $customMessages);
